crypto_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: project-postgres
      user: crypto_user
      password: crypto_pass
      port: 5432
      dbname: crypto_db
      schema: public
      threads: 2
      keepalives_idle: 0
      search_path: "public"